### PR TITLE
SSPROD-1566 increase onprem audit limit

### PR DESCRIPTION
**Pull request by haresh-suresh**
SSPROD-1566 increase onprem audit limit

### CODE REVIEW

**Comment by figarocorso** [comment]
@haresh-suresh Let's merge this against `onprem-2019-09` instead of `dev` if we want this to be available at next onprem release.

**Comment by haresh-suresh** [comment]
> @haresh-suresh Let's merge this against `onprem-2019-09` instead of `dev` if we want this to be available at next onprem release.

I was planning to give another PR / cherry-pick against the on prem branch, once this is reviewed / approved.

**Comment by papajulio** [comment]
Can you prepare the PR now that this is merged @haresh-suresh ? Thanks!

**Comment by marojor** [comment]
@papajulio this changes has been reverted with #324

@janoe found a problem when no quotes are being used:

https://sysdigcloud.slack.com/archives/C91Q9A56E/p1567700704012700?thread_ts=1567633550.011300&cid=C91Q9A56E

**Pull request merged**
