### PR TITLE
SSPROD-2383: anchore upgrade 0.5

### PR DESCRIPTION
**Pull request by haresh-suresh**
SSPROD-2383: anchore upgrade 0.5

### CODE REVIEW

**Comment by haresh-suresh** [comment]
> Overall this is fine. Are there any major changes that should be noted in the documentation? I

I don't think so, we have already worked with the doc team to capture most of it.

**Comment by papajulio** [comment]
@haresh-suresh this repo it's being deprecated please can you work with @jpravin and/or @bjhaid about porting this change to the configurator repo? CC @wpalmeri 

Would be good to notify all devs about the deprecation of this repo for following releases so we don't waste effort here and start giving more attention to the configurator repo.

**Comment by wpalmeri** [comment]
I'm ok with meeting this but it needs to also go in configurator repo. This repo isn't yet publicly deprecated.

**Comment by bjhaid** [comment]
I'll create a ticket to get this into configurator

**Comment by bjhaid** [comment]
ticket created

**Comment by haresh-suresh** [comment]
> I'll create a ticket to get this into configurator

Can you add me as a watcher to that ticket, so that I can understand the changes needed in the new repo ? Thanks !

**Comment by bjhaid** [comment]
> Can you add me as a watcher to that ticket, so that I can understand the changes needed in the new repo ? Thanks !

Done

**Comment by haresh-suresh** [comment]
Can we merge this in the meanwhile ?

**Pull request merged**
